### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zc.beforestorage#4]
@jimfulton @jamur2 @jamur2

You are the three heroes who are allowed to make a PyPI release of this package.
Could one of you please do so or give me ('icemac') the rights to do so?

**Comment by jugmac00** [comment]
@satchit is also maintainer at PyPi.

**Comment by jamur2** [comment]
Based on zopefoundation/developers and zopefoundation/administrators github membership, this seems safe, so granted "Maintainer" access to unblock you.  I'll leave it up to @jimfulton to grant Owner-level access.  Also, I probably shouldn't be an owner anymore, I haven't been involved in the community for a while now.

**Comment by icemac** [comment]
Thank you @jamur2, I just released https://pypi.org/project/zc.beforestorage/0.6/.
